/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ba.telas;

import br.ba.beans.Divida;
import br.ba.beans.Pagamento;
import br.ba.dao.DividaDAO;
import br.ba.dao.PagamentoDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author mathe
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        tablePagamento.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
 public void readTable() { 
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();
        
        for (Pagamento p : pdao.read()) {
            modelo.addRow(new Object[]{
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }
        public void readJTableIdDaDivida(int divida) {
        
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();

        for (Pagamento p : pdao.readForIdDivida(divida)) {
            modelo.addRow(new Object[]{
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePagamento = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPesqPag = new javax.swing.JTextField();
        txtIDDividaPag = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        txtDatPag = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblJuros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data do Pagamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Juros:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID da Dívida:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Valor Pago:");

        tablePagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Dívida", "Valor Pago", "Data"
            }
        ));
        tablePagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePagamento);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed1(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pesquisar pagamento:(ID da Dívida)");

        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblJuros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJuros.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesqPag, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(19, 19, 19)))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(86, 86, 86)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblJuros)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIDDividaPag, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorPago, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatPag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtIDDividaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblJuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesqPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePagamentoMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (tablePagamento.getSelectedRow() != -1) {
            txtIDDividaPag.setText(tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 1).toString());
            txtValorPago.setText(tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 2).toString());
            txtDatPag.setText(tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_tablePagamentoMouseClicked

    private void btnPesquisarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed1
        // TODO add your handling code here:
        readJTableIdDaDivida(Integer.parseInt(txtPesqPag.getText()));
    }//GEN-LAST:event_btnPesquisarActionPerformed1

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        
                 try {
            // TODO add your handling code here:
            Pagamento p = new Pagamento();
            PagamentoDAO dao = new PagamentoDAO();
            Divida d = new Divida();
            DividaDAO daoDiv = new DividaDAO();
            //p = dao.readForIdDividaUnica(Integer.parseInt(txtIDDividaPag.getText()));
            d = daoDiv.readDivida(Integer.parseInt(txtIDDividaPag.getText()));
            SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate = formatDate.parse(txtDatPag.getText());
            java.sql.Date sqlDate = new java.sql.Date(invoiceDate.getTime());
            
            if(d!= null && d.isPago()){
               JOptionPane.showMessageDialog(null, "Esta dívida já está paga", "ERRO AO PAGAR", ERROR);
            }else{
                if (Double.parseDouble(txtValorPago.getText()) < d.getValorDivida()){
                    JOptionPane.showMessageDialog(null, "O valor digitado é inferior ao valor da dívida");
                }else{
                    // Se a data de atualização for menor que a data de pagamento.
                    if(d.getDataAtualizacao().compareTo(sqlDate) < 0){
                        double multa, juros;
                        multa = Double.parseDouble(txtValorPago.getText()) * 1.02;
                        juros = multa * 1.0035;
                        lblJuros.setText(Double.toString(juros));
                        Divida divida = new Divida();
                     ////////   p.setId(Integer.parseInt(txtIdPag.getText()));
                        p.setDivida(new Divida(Integer.parseInt(txtIDDividaPag.getText())));
                        p.setValorPago(juros);
                        p.setDataPagamento(sqlDate);
                        dao.create(p);
                       
//                        txtIvidaPag.setText("");
//                        txtValorPago.setText("");
//                        txtDatPag.setText("");
//                        
                        readTable();
                    }else{
                       
                        Divida divida = new Divida();
                        divida.setCodigo(Integer.parseInt(txtIDDividaPag.getText()));
                   //     p.setId(Integer.parseInt(txtIdPag.getText()));
                        p.setDivida(divida);
                        //p.setValorPago(juros);
                        p.setDataPagamento(sqlDate);
                        dao.create(p);
                        txtIDDividaPag.setText("");
                        txtValorPago.setText("");
                        txtDatPag.setText("");
                        
                        readTable();
                    }
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Verifique se o formato da data está correto.", "ERRO AO ADICIONAR", ERROR);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate = formatDate.parse(txtDatPag.getText());
            java.sql.Date sqlDate = new java.sql.Date(invoiceDate.getTime());
            
            if (tablePagamento.getSelectedRow() != -1 ) {
                
                Pagamento p = new Pagamento();
                PagamentoDAO dao = new PagamentoDAO();
                p.setId((int) tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 0));
                p.setValorPago(Integer.parseInt(txtValorPago.getText()));
                p.setDataPagamento(sqlDate);
                
                dao.update(p);
                
                txtIDDividaPag.setText("");
                txtValorPago.setText("");
                txtDatPag.setText("");
                
                readTable();
                
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Verifique se o formato da data está correto.", "ERRO AO ATUALIZAR", ERROR);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if (tablePagamento.getSelectedRow() != -1) {
        Pagamento p = new Pagamento();
        PagamentoDAO dao = new PagamentoDAO();
        p.setId((int) tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 0));
        
        dao.delete(p);
        
        txtIDDividaPag.setText("");
        txtValorPago.setText("");
        txtDatPag.setText("");
        
        readTable();
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJuros;
    private javax.swing.JTable tablePagamento;
    private javax.swing.JTextField txtDatPag;
    private javax.swing.JTextField txtIDDividaPag;
    private javax.swing.JTextField txtPesqPag;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
